<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var backend\models\Project $model
 */

$this->title = $model->description; //CHANGED MVW 03/20/14: from id
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-view">

	<h1><?= Html::encode($this->title) ?></h1>

	<p>
		<?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
		<?php echo Html::a('Delete', ['delete', 'id' => $model->id], [
			'class' => 'btn btn-danger',
			'data' => [
				'confirm' => Yii::t('app', 'Are you sure to delete this item?'),
				'method' => 'post',
			],
		]); ?>
	</p>

	<?php echo DetailView::widget([
		'model' => $model,
		'attributes' => [
      // 'id',
      // 'is_active',
      // 'tenant_id',
      // 'tenant_dbu',
      // 'is_template',
			'project_number',
			'description',
			'comment:ntext',
			'type',
      // 'x_address_id',
			'construction_classification_id',
			'project_status_picklist_id',
      // 'sponsor_entity_id',
      // 'client_entity_id',
      // 'lead_picklist_id',
      // 'is_track_loan',
      // 'is_track_draw',
      // 'is_track_lien',
      // 'is_track_progress',
      // 'is_track_quality',
      // 'is_track_cost',
      // 'is_track_compare',
      // 'is_track_history',
      // 'is_track_qto',
      // 'is_track_schedule',
      // 'is_track_purchase',
      // 'is_route',
			'project_document_picklist_id',
			'percent_retainage',
			'percent_variance',
      // 'need_picklist_id',
      // 'purpose_picklist_id',
      // 'property_use',
			'loan_number',
      // 'account_number',
			'loan_classification_id',
      // 'can_pull_credit',
      // 'can_lock_loan',
			'appraised_value',
			'loan_amount',
			'ltv',
      // 'loan_balance',
      // 'loan_term',
      // 'loan_term_remaining',
      // 'rate_interest',
      // 'is_rate_fixed',
      // 'points',
      // 'loan_fees',
      'date_close',
			'date_maturity',
      // 'date_reprice',
      // 'date_balloon',
      // 'is_first_time:datetime',
      // 'is_first_position',
      // 'is_long_term',
      // 'is_waive_escrow',
      // 'down_payment',
      // 'payment_max',
      // 'payment_pi',
      // 'payment_total',
      // 'is_payment_fixed',
      // 'is_current_on_payments',
      // 'equity_in_property',
      // 'subordination_amount',
      // 'cash_out_amount',
      // 'property_tax',
      // 'hazard_insurance',
      // 'is_pmi',
      // 'date_end_pmi',
      // 'amount_pmi',
      // 'date_purchase',
      // 'selling_price',
      // 'purchase_price',
      // 'is_fsbo',
      // 'date_listing',
      // 'is_listing_expired',
      // 'gross_rent',
      // 'rate_occupancy',
      // 'date_start',
      // 'date_finish',
      // 'date_finish_estimated',
      // 'benchmarks:ntext',
      // 'damages:ntext',
      // 'work_week',
      // 'work_day',
      // 'cost_land',
      // 'cost_design',
      // 'cost_permit',
      // 'cost_site',
      // 'cost_gc',
      // 'cost_building',
      // 'cost_bond',
      // 'cost_insurance',
      // 'cost_contingency',
      // 'cost_fee',
      // 'cost_soft',
      // 'cost_ti',
      // 'cost_ffe',
      // 'location_factor',
      // 'inflation_factor',
      // 'sf_cost_site',
      // 'sf_cost_building',
      // 'sf_cost_ti',
      // 'sf_cost_total',
      // 'percent_gc',
      // 'percent_permit',
      // 'percent_design',
      // 'percent_bond',
      // 'percent_insurance',
      // 'percent_contingency',
      // 'percent_fee',
      // 'percent_soft',
      // 'template_project_id',
			'folder',
			'date_archive',
			'note:ntext',
			'create_time',
			'created_by_entity_id',
			'update_time',
			'updated_by_entity_id',
		],
	]); ?>

</div>
